### ISSUE TITLE
Unable to get the word 'आश्चर्य' in Hindi

### ISSUE THREAD

**Issue by YaminiVijayan** [varnamproject/libvarnam#132]
See here: pg 7
![ascharya](https://cloud.githubusercontent.com/assets/11420496/9519326/634e261e-4cdb-11e5-8a58-608bfde1dfc0.png)

This link: https://storyweaver.org.in/stories/679-raju-aur-tarakari

**Comment by purvishah77** [comment]
@navaneeth hi navaneeth. can this be fixed?

**Comment by purvishah77** [comment]
@navaneeth hi pl do update.

**Comment by purvishah77** [comment]
@navaneeth hi pl do update.

**Comment by jijeshmohan** [comment]
Hi @purvishah77  In varnam website we are able to get the word . Please check the image below 
<img width="485" alt="screen shot 2015-09-10 at 8 05 32 am" src="https://cloud.githubusercontent.com/assets/43115/9778793/ef8decc4-5792-11e5-96ef-ea4d1e617454.png">

**Comment by purvishah77** [comment]
@jijeshmohan thanks for the quick revert. really appreciate the same. 
 Its available on google input  aashcharya. Does that help? What other inputs could we give to help on this. Shall we connect you to on of our language editors.


![unnamed](https://cloud.githubusercontent.com/assets/10954914/9780168/9bc37a90-57a2-11e5-861c-bf28b5244cd0.png)

**Comment by jijeshmohan** [comment]
Varnam learned that word and now you will get this word even with `aashcharya` , Please let us know if it is not working in Pratham platform 
<img width="326" alt="screen shot 2015-09-10 at 10 04 37 am" src="https://cloud.githubusercontent.com/assets/43115/9780221/b528f4dc-57a3-11e5-9be4-6c62c7686e1b.png">

**Comment by purvishah77** [comment]
thanks @jijeshmohan 
@YaminiVijayan pl confirm
