### ISSUE TITLE
Unable to choose word-prompt (in languages) by clicking on it 

### ISSUE THREAD

**Issue by purvishah77** [varnamproject/libvarnam#139]
When you start typing in any language (but English), a word prompt appears. But you can only choose it by pressing enter or space. Ideally, user must be able to choose the word by clicking on it as well, which is not possible now.

**Comment by navaneeth** [comment]
Hi Purvi,

This works well on the online editor which varnam has (https://www.varnamproject.com/editor). 

This bug has nothing to do with how `libvarnam` works. This can be easily implemented on the story weaver because the UI that is displayed is implemented separately in the story weaver
