### ISSUE TITLE
Use of ml.full.tar.gz

### ISSUE THREAD

**Issue by subins2000** [varnamproject/libvarnam#144]
Hey.

I downloaded [ml.tar.gz](http://ftp.yzu.edu.tw/nongnu/varnamproject/words/ml/ml.tar.gz) and I was able to successfully import it to varnam.

But I can't import files in [ml.full.tar.gz](http://ftp.yzu.edu.tw/nongnu/varnamproject/words/ml.full.tar.gz) as it is in JSON format. Is this file for importing into varnam ?

**Comment by navaneeth** [comment]
`varnamc` has a `import-learning-from` option. This file will be used there. This is a separate format which contains all learned data so that importing will be much easier as varnam don't have to perform learn again

**Comment by subins2000** [comment]
This should be documented. I have made a pull request #145
